In [5]:
import numpy as np

### 打印numpy的版本和配置说明

In [6]:
print(np.__version__)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/Anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/Anaconda\\Library\\include']
blas

In [10]:
np.zeros((10,10))
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 找到一个数组的内存大小

In [11]:
z = np.zeros((10,10))
print("%d bytes" % (z.size*z.itemsize))

800 bytes


### 从命令行中得到numpy中add函数的说明文档

In [12]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

### 6.创建一个长度为10并且除了第5个值为1的空向量

In [13]:
z = np.zeros(10)
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [16]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8.反转一个向量

In [18]:
z = np.arange(50)
z=z[::-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 9.创建一个3x3并且值从0到8的矩阵

In [20]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10.找到数组【1，2，0，0，4，0】中非0元素的位置索引

In [21]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

In [25]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.random.random((3,3,3))

array([[[0.8741569 , 0.89655038, 0.36646452],
        [0.30396177, 0.87168118, 0.41237981],
        [0.7648103 , 0.2516245 , 0.12373018]],

       [[0.12150597, 0.49993745, 0.04436276],
        [0.86170115, 0.22308076, 0.34878754],
        [0.0859888 , 0.32066301, 0.57294112]],

       [[0.94895805, 0.97381378, 0.24848177],
        [0.18830201, 0.17653977, 0.97754038],
        [0.29524766, 0.87526347, 0.41768256]]])

In [31]:
z = np.random.random((10,10))
zmax,zmin=z.max(),z.min()
zmax,zmin


(0.9321554928134758, 0.007300297310803616)

In [34]:
z = np.random.random(30)
zmean=z.mean()
zmean

0.5069721739930958

### 15.创建一个二维数组，边界值为1，其余为0

In [37]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 16.对于一个存在的数组，如何添加一个用0填充的边界

In [38]:
z = np.ones((5,5))
z = np.pad(z,pad_width=1,mode="constant",constant_values=0)
z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [42]:
0*np.nan

nan

In [43]:
np.nan == np.nan

False

In [44]:
np.inf > np.nan

False

In [45]:
np.nan - np.nan

nan

In [46]:
0.3 == 3*0.1

False

### 18.创建一个5x5的矩阵，并设置1，2，3，4落在其对角线的下方

In [52]:
z = np.diag(1+np.arange(4),k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 19.创建一个8x8矩阵，并且设置成棋盘样式

In [53]:
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [54]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

### 21.用tile函数去创建一个8x8的棋盘样式矩阵

In [59]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 22.对一个5x5的随机矩阵做归一化

In [61]:
z = np.random.random((5,5))
zmax,zmin = z.max(),z.min()
z = (z - zmin)/(zmax - zmin)
z

array([[0.89343852, 0.17153253, 0.06406985, 0.13279532, 0.29267643],
       [0.57512235, 0.2563795 , 0.3859579 , 0.23315898, 0.67590222],
       [0.54306959, 0.3929534 , 0.68522996, 1.        , 0.71520974],
       [0.12337349, 0.        , 0.7345491 , 0.94228981, 0.10973122],
       [0.83935405, 0.11399809, 0.15932316, 0.14293792, 0.31398043]])

### 23.创建一个将颜色描述为rgba四个无符号字节的自定义dtype

In [62]:
color = np.dtype([("r",np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [63]:
np.dot(np.ones((5,3)),np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [64]:
z = np.arange(11)
z[(3<z)&(z<=8)]*=-1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [70]:
sum(range(5),-1)

10

In [71]:
from numpy import *
print(sum(range(5),-1))

10


In [76]:
print(np.array(0) / np.array(0))

nan


E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


### 29. 如何从零位对浮点数组做舍入 ?

In [79]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 3. -4.  8. -1.  2.  5.  1.  8.  1. -9.]


In [80]:
Z1 = np.random.randint(0,10,10)
Z1

array([4, 6, 4, 0, 8, 6, 6, 2, 6, 6])

### 33. 如何得到昨天，今天，明天的日期? 

In [81]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-06
Today is 2019-08-07
Tomorrow is 2019-08-08


In [84]:
today     = np.datetime64('today', 'D')
str(today)

'2019-08-07'

### 34. 如何得到所有与2016年7月对应的日期？

In [88]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [93]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [94]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [95]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [96]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

### 36. 用五种不同的方法去提取一个随机数组的整数部分

In [103]:
z = np.random.uniform(0,10,10)
z - z%1

array([4., 7., 5., 5., 6., 0., 4., 3., 8., 5.])

In [105]:
np.floor(z)

array([4., 7., 5., 5., 6., 0., 4., 3., 8., 5.])

### 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4 

In [107]:
Z = np.zeros((5,5))
Z += np.arange(2,7)
print (Z)

[[2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]]


### 38. 通过考虑一个可生成10个整数的函数，来构建一个数组

In [111]:
def generate():
    for x in range(10):
        yield x
np.fromiter(generate(),dtype=float,count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 

In [112]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [122]:
z = np.random.random(10)
z.sort()
z

array([0.13231093, 0.14482373, 0.20433923, 0.23637665, 0.33524477,
       0.36265728, 0.49336644, 0.5471386 , 0.55014694, 0.9322211 ])

In [124]:
A = np.random.randint(0,2,5)
A

array([0, 1, 1, 1, 0])

### 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [128]:
Z = np.random.random((10,2))
Z


array([[0.34081962, 0.9184049 ],
       [0.38930918, 0.66138155],
       [0.56721367, 0.43736337],
       [0.4643812 , 0.06867381],
       [0.57948243, 0.41989797],
       [0.83414708, 0.90538408],
       [0.0480519 , 0.1291693 ],
       [0.9381564 , 0.7461874 ],
       [0.37377687, 0.51284675],
       [0.18483902, 0.17953862]])

In [129]:
X,Y = Z[:,0], Z[:,1]
X,Y

(array([0.34081962, 0.38930918, 0.56721367, 0.4643812 , 0.57948243,
        0.83414708, 0.0480519 , 0.9381564 , 0.37377687, 0.18483902]),
 array([0.9184049 , 0.66138155, 0.43736337, 0.06867381, 0.41989797,
        0.90538408, 0.1291693 , 0.7461874 , 0.51284675, 0.17953862]))

In [132]:
R = np.sqrt(X**2+Y**2)
R


array([0.9796048 , 0.76745501, 0.71625279, 0.46943157, 0.71562154,
       1.23106526, 0.13781761, 1.19872143, 0.63460298, 0.25768116])

In [133]:
T = np.arctan2(Y,X)
T

array([1.21544963, 1.0387789 , 0.65685223, 0.14681831, 0.62705161,
       0.82632713, 1.21465213, 0.67191527, 0.94098381, 0.77085272])

### 45. 创建一个长度为10的向量，并将向量中最大值替换为1

In [139]:
z = np.random.random(10)
z[z.argmax()]=1
z

array([0.12068447, 0.27326483, 0.69571233, 0.30693671, 0.00969714,
       0.69065128, 1.        , 0.35075991, 0.95960582, 0.79403542])